name: CI-CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      # copia o meu código
      - uses: actions/checkout@v3
      
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      
      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          # onde buscar o arquivo de build e seu caminho
          context: ./src
          file: ./src/Dockerfile
          # realização do push para o registre com as tags latest e a atual
          push: true
          tags: |
            jp0user0docker/rotten-potatoes:latest
            jp0user0docker/rotten-potatoes:v${{ github.run_number }}
          
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      
      - name: Deploy to k8s cluster
        uses: Azure/k8s-deploy@v3.0
        with:
          images: jp0user0docker/rotten-potatoes:v${{ github.run_number }}
          manifests: |
            k8s/web/deployment.yaml
         
         


